### ISSUE TITLE
Dangerous: genericLength

### ISSUE THREAD

**Issue by tomjaguarpaw** [NorfairKing/haskell-dangerous-functions#11]
[`genericLength`](https://www.stackage.org/haddock/lts-18.12/base-4.14.3.0/Data-List.html#v:genericLength) is almost never going to be what one wants to use in practice.

(I volunteer to add this to the list but it will take time for me to get round to it.)

**Comment by NorfairKing** [comment]
Sounds like a good idea but can you give me more details please?

**Comment by tomjaguarpaw** [comment]
The definition of `genericLength` is as below. It is O(n) in space except in the case of a lazy numeric type that can be partially consumed (e.g. `data Nat = Z | S Nat`). The use of a lazy numeric type must so rare that having `genericLength` in the very important base module `Data.List` seems a mistake.

There is a note in the Haddock

> It is, however, less efficient than 'length'.

Rather an understatement!

```haskell
genericLength           :: (Num i) => [a] -> i
genericLength []        =  0
genericLength (_:l)     =  1 + genericLength l
```

**Comment by NorfairKing** [comment]
Ah so if I understand right, this is like `foldl (+) 0` instead of `fodll' (+) 0`?
So we want to recommend `fromIntegral . length` instead?

**Comment by tomjaguarpaw** [comment]
> Ah so if I understand right, this is like foldl (+) 0 instead of fodll' (+) 0?

Yes exactly

> So we want to recommend fromIntegral . length instead?

That's probably a good idea for most cases.  `length` returns an `Int` so there are questions to be asked about overflow, but if one is taking the length of a list and it won't fit in even 32 bits then there are bigger problems around.

**Comment by tomjaguarpaw** [comment]
(In fact I'm inclined to say if you're using lists at all there are bigger problems around)

**Comment by NorfairKing** [comment]
Jup, that sounds like a real problem. Let's add it.
