### ISSUE TITLE
Dangerous: fromString (instance IsString ByteString)

### ISSUE THREAD

**Issue by tomjaguarpaw** [NorfairKing/haskell-dangerous-functions#12]
It silently truncates Unicode characters: https://twitter.com/ChShersh/status/1442800460268720128

(I volunteer to add this to the list but it will take some time.)

**Comment by NorfairKing** [comment]
It does what?! Yes let's add it.

**Comment by tomjaguarpaw** [comment]
Here is the evidence:

* [`fromString`](https://hackage.haskell.org/package/bytestring-0.10.8.2/docs/src/Data.ByteString.Internal.html#line-179) is `packChars`
* [`packChars`](https://hackage.haskell.org/package/bytestring-0.10.8.2/docs/src/Data.ByteString.Internal.html#packChars) calls `unsafeLenPackChars`
* [`unsafeLenPackChars`](https://hackage.haskell.org/package/bytestring-0.10.8.2/docs/src/Data.ByteString.Internal.html#unsafePackLenChars) pokes a `Word8` for each character, via `c2w`
* [`c2w1`](https://hackage.haskell.org/package/bytestring-0.10.8.2/docs/src/Data.ByteString.Internal.html#c2w) says

  > Unsafe conversion between 'Char' and 'Word8'. This is a no-op and
  silently truncates to 8 bits Chars > '\255'. It is provided as
  convenience for ByteString construction.

  I don't actually understand what that means. How is it a no-op and also truncates? Anyway, it does truncate, or "wrap":

  ```
  > fromIntegral (256 + 26) :: Word8
  26
  ```

So, if you use `fromString :: String -> ByteString` and you have non-ASCII characters then you get garbage out.

**Comment by NorfairKing** [comment]
Oh goodie. Yes let's add it.
