### ISSUE TITLE
how to get warnings from this rule set exclusively?

### ISSUE THREAD

**Issue by jwaldmann** [NorfairKing/haskell-dangerous-functions#18]
How do I enable just the warnings/suggestions provided by this module? I tried
```
hlint --hint=hlint.yaml src/ 
```
but this will use hlint's built-in rules as well - I think that's the meaing of the first to lines of `.. -v ..` output
```
# Initialise of global flags... took 0.00s
# Config of data/hlint.yaml... took 0.17s
# Config of hlint.yaml... took 0.00s
# Parse of src/...
```

I tried to put `- ignore: { }` at the start, but then I get no output at all (I think that's https://github.com/ndmitchell/hlint/issues/748)

**Comment by NorfairKing** [comment]
That's something you should ask on the hlint issue tracker, not here, because I have no clue..

**Comment by NorfairKing** [comment]
Seems to be fixed.
