### ISSUE TITLE
Incorrect information on `unsafeInterleaveIO`

### ISSUE THREAD

**Issue by Melvar** [NorfairKing/haskell-dangerous-functions#23]
The list claims that `unsafeInterleaveIO` uses `unsafeDupablePerformIO`. It does not; it is defined in terms of `unsafeDupableInterleaveIO`, which in turn is defined directly by state token plumbing. My guess is that this is either a typo or a misreading of the definition of `unsafeInterleaveIO` (the names do share three of their four words).

**Comment by NorfairKing** [comment]
Doh, PR welcome.
