### ISSUE TITLE
Extend "safe" alternatives

### ISSUE THREAD

**Issue by Bodigrim** [NorfairKing/haskell-dangerous-functions#26]
Thanks for maintaining this list! Just a couple of random suggestions:

* Suggest `drop 1` as a substitute for `tail`.
* Suggest [`unsnoc`](https://ghc.gitlab.haskell.org/ghc/doc/libraries/base-4.19.0.0-inplace/Data-List.html#v:unsnoc) as a substitute for `init` / `last`, once GHC 9.8 is out.
* Suggest [`(!?)`](https://ghc.gitlab.haskell.org/ghc/doc/libraries/base-4.19.0.0-inplace/Data-List.html#v:-33--63-) as a substitute for `(!!)`, once GHC 9.8 is out.
* Suggest [`Data.Text.IO.Utf8`](https://hackage.haskell.org/package/text-2.1/docs/Data-Text-IO-Utf8.html) instead of `Data.Text.IO`.

If we are in agreement, I can prepare a PR.

**Comment by NorfairKing** [comment]
Yup I'm very happy with these. Also TIL about the last three :D 
PR welcome!
