### ISSUE TITLE
Real world incident with writeFile

### ISSUE THREAD

**Issue by tomjaguarpaw** [NorfairKing/haskell-dangerous-functions#8]
> If you can showcase a public incident with real-world consequences that happened because of one of these functions, I would love to refer to it in this document!

Today my public app crashed due to `writeFile` throwing an error when asked to write non-ASCII characters with `LC_ALL` and `LANG` not set. It *had* been working fine, then I changed the deployment method to use [nsjail](https://github.com/google/nsjail/). In my opinion getting rid of environment variables is a Good Thing(TM) but it exposed the `writeFile` issue. A paying customer could therefore not use the app.

(The fix I used was to explicitly convert to a UTF-8 `ByteString` and then `ByteString.writeFile` that.)

(I'm not sure I want to make the identity of the app public in this issue but I'm happy to send details privately.)

**Comment by NorfairKing** [comment]
I believe you! (This is a fairly common occurrence.) No need to make the identity of the app public.
You can add something like "Real world outage by @tomjaguarpaw on 2021-09-24" to the section if you want.
